"""empty message

Revision ID: 21166afba474
Revises: None
Create Date: 2016-03-12 12:58:47.033228

"""

# revision identifiers, used by Alembic.
revision = '21166afba474'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctor_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('middle_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.Column('gender', sa.String(length=1), nullable=False),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('blood_group', sa.String(length=3), nullable=False),
    sa.Column('mobile_number', sa.String(length=10), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('city', sa.String(length=64), nullable=False),
    sa.Column('country', sa.String(length=64), nullable=False),
    sa.Column('pincode', sa.String(length=6), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('doctor_info')
    ### end Alembic commands ###
