"""empty message

Revision ID: b83831b4b242
Revises: 21166afba474
Create Date: 2016-03-14 00:49:43.914692

"""

# revision identifiers, used by Alembic.
revision = 'b83831b4b242'
down_revision = '21166afba474'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('gender', sa.String(length=1), nullable=False),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('blood_group', sa.String(length=3), nullable=False),
    sa.Column('mobile_number', sa.String(length=10), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('city', sa.String(length=64), nullable=False),
    sa.Column('country', sa.String(length=64), nullable=False),
    sa.Column('pincode', sa.String(length=6), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_table('doctor_info')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctor_info',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('first_name', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('middle_name', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('last_name', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('gender', mysql.VARCHAR(length=1), nullable=False),
    sa.Column('dob', sa.DATE(), nullable=False),
    sa.Column('blood_group', mysql.VARCHAR(length=3), nullable=False),
    sa.Column('mobile_number', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('address', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('city', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('country', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('pincode', mysql.VARCHAR(length=6), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    ### end Alembic commands ###
